services:
  datasets:
    build: .
    container_name: datasets
    image: hiropppe/datasets
    #ports:
    #  - 8888:8888
    network_mode: host
    tty: true
    volumes:
      - .:/usr/src/develop
    command: ["bash"]

